using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DarkHeresy2CharacterCreator.Model.Talents
{
    /// <summary>
    /// Names of talents
    /// </summary>
    public enum TalentName
    {
        #region Core Rulebook common talents
        Ambidextrous,
        Blind_Fighting,
        Catfall,
        Clues_from_the_Crowds,
        Die_Hard,
        Disarm,
        Double_Team,
        Enemy,
        Ferric_Summons,
        Frenzy,
        Iron_Jaw,
        Jaded,
        Keen_Intuition,
        Leap_Up,
        Nowhere_to_Hide,
        Peer,
        Quick_Draw,
        Rapid_Reload,
        Resistance,
        Sound_Constitution,
        Takedown,
        Technical_Knock,
        Warp_Sense,
        Weapon_Tech,
        Weapon_Training,
        Armour_Monger,
        Battle_Rage,
        Bulging_Biceps,
        Combat_Master,
        Constant_Vigilance,
        Contact_Network,
        Coordinated_Interrogation,
        Counter_Attack,
        Cover_Up,
        Deny_the_Witch,
        Devastating_Assault,
        Double_Tap,
        Exotic_Weapon_Training,
        Face_in_a_Crowd,
        Hard_Target,
        Hardy,
        Hatred,
        Hip_Shooting,
        Independent_Targeting,
        Inescapable_Attack,
        Killing_Strike,
        Luminien_Shock,
        Maglev_Transcendence,
        Marksman,
        Mechandendrite_Use,
        Precision_Killer,
        Prosanguine,
        Strong_Minded,
        Swift_Attack,
        Two_Weapon_Wielder,
        Unarmed_Specialist,
        Warp_Conduit,
        Whirlewind_of_Death,
        Adamantium_Faith,
        Assassin_Strike,
        Bastion_of_Iron_Will,
        Blademaster,
        Crushing_Blow,
        Deathdealer,
        Delicate_Interrogation,
        Eye_of_Vengence,
        Favoured_by_the_Warp,
        Flash_of_Inside,
        Halo_of_Command,
        Hammer_Blow,
        Infused_Knowledge,
        Lightning_Attack,
        Luminien_Blast,
        Mastery,
        Mighty_Shot,
        Never_Die,
        Preternatural_Speed,
        Sprint,
        Step_Aside,
        Superior_Chirurgeon,
        Target_Selection,
        Thunder_Charge,
        True_Grit,
        Two_Weapon_Master,
        Warp_Lock
        #endregion Core Rulebook common talents
    }
}
