using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DarkHeresy2CharacterCreator.Model.Equipment.Enums
{
    public enum WeaponName
    {   //todo: think about bind number to type
        Bolt_Pistol,
        Boltgun,
        Heavy_Bolter,
        Storm_Bolter,
        Hand_Flamer,
        Flamer,
        Hevy_Flamer,
        Laspistiol,
        Lasgun,
        Laslock,
        Long_Las,
        Hotshot_Laspistol,
        Hotshot_Lasgun,
        Grenade_Launcher,
        Missile_Launcher,
        Bolas,
        Bow,
        Crossbow,
        Inferno_Pistol,
        Meltagun,
        Plasma_Pistol,
        Plasma_Gun,
        Autopistol,
        Autogun,
        Autocannon,
        Hand_Cannon,
        Heavy_Stubber,
        Shotgun,
        Shotgun_Combat,
        Sniper_Rifle,
        Stub_Automatic,
        Stub_Revolver,
        Grav_Pistol,
        Graviton_Gun,
        Needle_Pistol,
        Needle_Rifle,
        Web_Pistol,
        Webber,
        Blind_Grenade,
        Choke_Grenade,
        Frag_Grenade,
        Hallucinogenic_Grenade,
        Haywire_Grenade,
        Krak_Grenade,
        Photon_Flash_Grenade,
        Smoke_Grenade,
        Stun_Grenade,
        Web_Grenade,
        Frag_Missile,
        Krak_Missile,
        Fire_Bomb,
        Melta_Bomb,
        Chainaxe,
        Chainblade,
        Chainsword,
        Eviscerator,
        Force_Sword,
        Force_Staff,
        Great_Weapon,
        Hunting_Lance,
        Improvised,
        Knife,
        Shield,
        Spear,
        Staff,
        Sword,
        Trucheon,
        Warhammer,
        Whip,
        Omnissian_Axe,
        Power_Fist,
        Power_Sword,
        Power_Axe,
        Power_Maul_Heigh,
        Power_Maul_Low,
        Shock_Maul,
        Shock_Whip
    }
}
